FROM eclipse-temurin:17-jdk-alpine


WORKDIR /app


COPY pom.xml .


RUN ./mvnw dependency:go-offline -B


COPY src ./src


RUN ./mvnw package -DskipTests


EXPOSE 8080

CMD ["java", "-jar", "target/mvc_rest-0.0.1-SNAPSHOT.jar"]

